FROM node:22-bookworm-slim

WORKDIR /app/packages/web

RUN corepack enable

COPY packages/web/package.json /app/packages/web/package.json

RUN pnpm install --no-frozen-lockfile

COPY packages/web /app/packages/web

EXPOSE 3005

CMD ["pnpm", "dev"]
